export const fallback = [
    {
        sr_no: 4,
        namc_id: 4,
        nam_code: "AA",
        code_system: "NAMASTE",
        display: "vātavyādhiḥ / वातव्याधिः",
        icd_code: null,
        long_definition: "",
        ontology_branches: "",
        short_definition: "",
        source: "NAMASTE",
        system: "Ayurveda",
        term: "vAtavyAdhiH",
    },
    {
        sr_no: 5,
        namc_id: 5,
        nam_code: "AAA",
        code_system: "vAta",
        display: "dōṣāvasthā (vāta) / दोषावस्था (वात)",
        icd_code: null,
        long_definition: "",
        ontology_branches: "",
        short_definition: "",
        source: "NAMASTE",
        system: "Ayurveda",
        term: "doShAvasthA (vAta)",
    },
    {
        sr_no: 8,
        namc_id: 8,
        nam_code: "SR10",
        code_system: "NAMASTE",
        display: "(a) vātaprakopaḥ / वातप्रकोपः",
        icd_code: "AAA-2.1",
        long_definition: "It is characterized by abdominal pain and increased gaseous movements in abdomen. This may be explained by aggravation of vatadosha at its designated site and preparing to cause certain morbidity.",
        ontology_branches: "",
        short_definition: "",
        source: "NAMASTE",
        system: "Ayurveda",
        term: "vAtaprakopaH",
    },
    {
        sr_no: 6,
        namc_id: 6,
        nam_code: "SR11",
        code_system: "NAMASTE",
        display: "(a) vātasañcayaḥ / वातसञ्चयः",
        icd_code: "AAA-1",
        long_definition: "It is characterized by impaired movements of vāta, fullness of abdomen and aversion to factors causing of increase of vāta such as cold. This may be explained by accumulation of vatadosha at the designated site to a moderate level resulting in accumulation.",
        ontology_branches: "",
        short_definition: "",
        source: "NAMASTE",
        system: "Ayurveda",
        term: "vAtasa~jcayaH",
    },
    {
        sr_no: 7,
        namc_id: 7,
        nam_code: "SR12",
        code_system: "NAMASTE",
        display: "(a) vātavṛddhiḥ / वातवृद्धिः",
        icd_code: "AAA-2",
        long_definition: "It is characterized by roughness or hoarseness of voice, emaciation, blackish discoloration of body, twitching in various parts of body, desire for warmth, insomnia, reduced physical strength, hard stools. This may be explained by marked increase of vatadosha functions and consequent physiological and pathological ramifications.",
        ontology_branches: "",
        short_definition: "",
        source: "NAMASTE",
        system: "Ayurveda",
        term: "vAtavRuddhiH",
    },
    {
        sr_no: 9,
        namc_id: 9,
        nam_code: "AAA-2.2",
        code_system: "NAMASTE",
        display: "prāṇavātakōpaḥ / प्राणवातकोपः",
        icd_code: null,
        long_definition: "the disorder is characterized by hikkā [hiccup], śvāsa [breathlessness/difficult breathing], cakṣurādīnāmupaghāta [impairment of sense organs viz. eye], pīnasa [cold, catarrh], ardita [facial paralysis], tr̥ṭ [thirst], kāsaḥ [cough]",
        ontology_branches: "",
        short_definition: "",
        source: "NAMASTE",
        system: "Ayurveda",
        term: "prANavAtakopaH",
    },
    {
        sr_no: 10,
        namc_id: 10,
        nam_code: "AAA-2.3",
        code_system: "NAMASTE",
        display: "udānavātakōpaḥ / उदानवातकोपः",
        icd_code: null,
        long_definition: "the disorder is characterized by kaṇṭharōdha [choking of throat/stopping or lowering voice], manōbhraṁśa [mental disturbance], chardiḥ [vomiting], arōcakaḥ [tastelessness], pīnasa [cold, catarrh], galagaṇḍaḥ [glandular swelling in jaw, neck and throat region /goitre], jatrūrdhvarōga [diseases of body above collar bone/diseases of head and neck]",
        ontology_branches: "",
        short_definition: "",
        source: "NAMASTE",
        system: "Ayurveda",
        term: "udAnavAtakopaH",
    },
];